Repository wearther/weather-app, pull requests merged in 2018-03, with the labels that each got.

#41 Forecast table
  index.html
Labels: content, design

#42 Making it look super good
  css/main.css
  index.html
Labels: design

#43 put the proper querys into the main.css
  css/main.css
Labels: dev

#44 fixed the spacing on the h1 to make lit look nicer
  css/main.css
  index.html
Labels: design

#47 Weekly forecast
  css/main.css
  index.html
Labels: dev

#48 Revert "Weekly forecast"
  css/main.css
  index.html
Labels: design

#49 restored correct weekly forcaest code and css
  css/main.css
  index.html
Labels: dev

#50 Teeny tiny fixes 2
  css/main.css
  index.html
Labels: design

#51 Fixing the image spacing hopefully
  css/main.css
  index.html
Labels: blocked, design

#52 styled current temperature for every screen size
  css/main.css
  index.html
Labels: dev

#53 added SEO
  index.html
Labels: enhancement

#54 Fixing the image spacing hopefully
  css/main.css
  images/heart-d.svg
  images/heart-f.svg
  images/heart.svg
  index.html
  js/bootstrap-3.3.7-dist/css/bootstrap-theme.css
  js/bootstrap-3.3.7-dist/css/bootstrap-theme.css.map
  js/bootstrap-3.3.7-dist/css/bootstrap-theme.min.css
  js/bootstrap-3.3.7-dist/css/bootstrap-theme.min.css.map
  js/bootstrap-3.3.7-dist/css/bootstrap.css
  js/bootstrap-3.3.7-dist/css/bootstrap.css.map
  js/bootstrap-3.3.7-dist/css/bootstrap.min.css
  js/bootstrap-3.3.7-dist/css/bootstrap.min.css.map
  js/bootstrap-3.3.7-dist/fonts/glyphicons-halflings-regular.svg
  js/bootstrap-3.3.7-dist/fonts/glyphicons-halflings-regular.woff2
  js/bootstrap-3.3.7-dist/js/bootstrap-dropdown.js
  js/bootstrap-3.3.7-dist/js/bootstrap.js
  js/bootstrap-3.3.7-dist/js/bootstrap.min.js
  js/bootstrap-3.3.7-dist/js/npm.js
  js/bootstrap-3.3.7-dist/js/popper.min.js
Labels: content, design, dev

#57 Centered main, fixed font-size, aligned small details
  css/main.css
  index.html
Labels: dev

#58 lets try this
  index.html
Labels: bug

#59 added icons
  ottawa.html
Labels: design

#60 Touch ups
  css/main.css
Labels: dev

#61 Applying style to other city pages
  css/main.css
  index.html
  ottawa.html
Labels: dev
